name: Build Release

on: 
  push:
    branches:
      - master
  workflow_dispatch:

env:
  packageName: "dev.raspichu.inspector-enhancements"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.packageName}}/package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ env.packageName }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ env.packageName }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV

      - name: Add changelog URL to package.json
        run: |
          jq --arg url "https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.prop }}" \
             '. + {changelogUrl: $url}' "${{ env.packageName }}/package.json" > tmp.json && mv tmp.json "${{ env.packageName }}/package.json"

      - name: Generate changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          FORMAT="- [[%h](https://github.com/${{ github.repository }}/commit/%H)]: %s"
          if [ -z "$PREV_TAG" ]; then
            LOG=$(git log --pretty=format:"$FORMAT")
          else
            LOG=$(git log --pretty=format:"$FORMAT" "$PREV_TAG"..HEAD)
          fi
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "## Changes" >> $GITHUB_ENV
          echo "$LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{env.packageName}}/"
          filename: "../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
          
      - run: find "${{env.packageName}}/" -name \*.meta >> metaList
          
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList
        
        
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          body: ${{ env.changelog }}
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            ${{ env.packageName }}/package.json

      - name: Trigger vpm-listing rebuild
        env:
          GH_TOKEN: ${{ secrets.VPM_LISTING_TOKEN }}
        run: gh workflow run build-listing.yml --repo raspichu/vpm-listing --ref main